#!/usr/bin/env bash
# copies file from directory to the server
# args are given when argc less than 4
# e.g. ./0-transfer_file some_page.html 35.227.79.31 ubuntu ~/.ssh/holberto
if [ $# -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
#	echo "scp -i $4 $1 $3@$2:~"
	scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2":~
fi
