#!/usr/bin/env bash
# installs nginx on the remote web server
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo systemctl start nginx
mkdir -p /var/www/html
sudo bash -c 'echo "Holberton School" > /var/www/html/index.html'
