#!/usr/bin/env bash
# installs nginx on the remote web server, then configures a 404
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo service nginx restart

sudo bash -c 'echo "Holberton School" > /var/www/html/index.html'
sudo sed -i "/# SSL configuration/$newstring/" /etc/nginx/sites-enabled/default
sudo service nginx restart

# 404 page
sudo bash -c "echo \"Ceci n'est pas une page\" > /usr/share/nginx/html/not_found.html"
newstring="error_page 404 /custom_404.html;
	location = /custom_404.html {
		root /usr/share/nginx/html;
		internal;
	}"
sudo sed -i "/# listen 443 ssl default_server;/$newstring/" /etc/nginx/sites-enabled/default
sudo service nginx nginx restart
