#!/usr/bin/env bash
# installing haproxy on a new server
sudo apt-get install software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-1.6
sudo apt-get -y update
sudo apt-get -y install haproxy=1.6.\*

# setup the config file
conf="listen www\
#--\
#Frontend\
#--\
#frontend main\
bind :80\
#option http-server-close\
#option forwardfor\
#default_backend app-main\
#--\
#Backend\
#--\
#backend app-main\
balance roundrobin\
server 1660-web-01 35.227.79.31:80 check\
server 1660-web-02 35.243.199.170:80 check"
sudo echo "$conf" | tee -a /etc/haproxy/haproxy.cfg 
sudo echo "ENABLED=1" | tee -a /etc/default/haproxy

sudo service haproxy restart
