#!/usr/bin/env bash
# change nginx setting to allow port 80
# must tart by getting nginx running
# use top to see processes
# pid is `pgrep -u root nginx`
# to see where it goes try nginx -s reload
# put pid into /run/nginx.pid file it belongs
# 	pgrep -u root nginx > /run/nginx.pid
# 	sudo service nginx restart
# changes the sites available file
# 	rm /etc/nginx/sites-enabled/default
# 	ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# remove ipv6 requirement
# sudo sed -i 's/ ipv6only=on;/;/' /etc/nginx/sites-available/default
# restart
# other option is to just literally replace the port number
sudo sed -i -e 's/8080/80/g' /etc/nginx/sites-enabled/default
sudo service nginx restart
