#!/usr/bin/env bash
# prints holberton with a for loop
i=0
while [ $i -lt 20 ]
do
	((i++))
	echo $i
	if [ $i -eq 4 ]
	then
		echo "bad luck from china"
	elif [ $i -eq 9 ]
	then
		echo "bad luck from japan"
	elif [ $i -eq 17 ]
	then
		echo "bad luck form italy"
	fi
	
done
