#!/usr/bin/env bash
# prints holberton with a for loop
i=0
while [ $i -lt 20 ]
do
	((i++))
	echo $i
	case $i in
		4)
			echo "bad luck from china"
			;;
		9)
			echo "bad luck from japan"
			;;
		17)
			echo "bad luck from italy"
			;;
		
	esac
done
