#!/usr/bin/env bash
# changes localhost and facebook
cp /etc/hosts ~/hosts.new
sudo sed -i 's/127.0.0.1 localhost/127.0.0.2 localhost'/ ~/hosts.new
echo "8.8.8.8	facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
