#!/usr/bin/env bash
# changes server to run nginx as nginx
sudo echo "user nginx;" | sudo tee -a /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo apt-get -y install lsof
# shellcheck disable=SC2046
sudo kill $(lsof -t -i:8080)
sudo service nginx restart
