#!/usr/bin/env bash
# changes server to run nginx as nginx
# sudo echo "user nginx;" | sudo tee -a /etc/nginx/nginx.conf
sudo sed -i "s/#user www-data;/user nginx;/g" /etc/nginx/nginx.conf 
sudo sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo apt-get -y install lsof
# shellcheck disable=SC2046
sudo kill $(sudo lsof -t -i:8080)
# sudo pkill apache2
# these next two lines i'm less sure about
sudo chmod 777 /etc/nginx/nginx.conf
sudo chown nginx:nginx /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
