#!/usr/bin/env bash
# changes server to run nginx as nginx
sudo sed -i "s/#user www-data;/user nginx;/g" /etc/nginx/nginx.conf 
sudo sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo pkill apache2
sudo chown nginx:nginx /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
